import React from 'react';
import { CheckCircle2, Trash2, HardDrive, Cpu, Wifi, ShieldCheck, Download, ArrowLeft, Terminal, FileText, RefreshCw } from 'lucide-react';
import { ExecutionReport } from '../types';

interface ExecutionReportModalProps {
  report: ExecutionReport | null;
  isOpen: boolean;
  onClose: () => void;
  onViewTerminal: () => void;
}

export const ExecutionReportModal: React.FC<ExecutionReportModalProps> = ({
  report,
  isOpen,
  onClose,
  onViewTerminal,
}) => {
  if (!isOpen || !report) return null;

  const handleDownloadReport = () => {
    const textContent = `================================================================================
           WINDOWS PERFORMANCE OPTIMIZER - EXECUTION AUDIT REPORT
================================================================================
Task Name:             ${report.taskTitle}
Execution Timestamp:   ${report.timestamp}
Execution Duration:    ${report.durationSeconds}s
Status:                ${report.success ? 'SUCCESS (0 Fatal Errors)' : 'FAILED'}

KEY RESULTS:
- Total Files Deleted:   ${report.filesDeleted.toLocaleString()} files
- Storage Space Freed:   ${report.spaceFreedMB > 1024 ? (report.spaceFreedMB / 1024).toFixed(2) + ' GB' : report.spaceFreedMB + ' MB'}
- Memory RAM Released:   ${report.memoryFreedMB} MB
- In-Use Locked Files:   ${report.lockedFilesSkipped} (Safely preserved without crash)

SERVICES & NETWORK:
${report.servicesRecycled.map((s) => `- Service Recycled:   ${s}`).join('\n')}
${report.networkActions.map((n) => `- Network Action:     ${n}`).join('\n')}

ITEMIZED ACTIONS LOG:
${report.detailedLogSummary.map((item) => `[OK] ${item}`).join('\n')}

================================================================================
Generated by Windows Performance Optimizer Suite
================================================================================`;

    const blob = new Blob([textContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Optimization_Report_${new Date().toISOString().slice(0, 10)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-in fade-in duration-200">
      <div
        className="w-full max-w-2xl bg-[#0F1423] border border-[#1F293D] rounded-xl shadow-2xl shadow-black/60 overflow-hidden font-sans text-slate-100 flex flex-col"
        role="dialog"
        aria-modal="true"
      >
        {/* Header */}
        <div className="bg-gradient-to-r from-[#064E3B]/60 via-[#0F172A] to-[#132035] px-6 py-4 border-b border-[#1F293D] flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="w-10 h-10 rounded-lg bg-emerald-500/20 border border-emerald-500/40 flex items-center justify-center text-emerald-400">
              <CheckCircle2 className="w-6 h-6" />
            </div>
            <div>
              <div className="text-[11px] font-bold text-emerald-400 uppercase tracking-wider flex items-center space-x-1.5">
                <span>Execution Successful</span>
                <span className="text-slate-500">•</span>
                <span className="text-slate-400 font-mono">{report.durationSeconds}s Duration</span>
              </div>
              <h3 className="text-base sm:text-lg font-bold text-slate-100">
                {report.taskTitle} Completed
              </h3>
            </div>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={handleDownloadReport}
              className="px-3 py-1.5 bg-[#161B2A] hover:bg-[#1E293B] text-slate-300 rounded-lg text-xs font-medium border border-[#1F293D] flex items-center space-x-1.5 transition-colors cursor-pointer"
              title="Download text audit log"
            >
              <Download className="w-3.5 h-3.5" />
              <span className="hidden sm:inline">Export Report</span>
            </button>
          </div>
        </div>

        {/* Content Body */}
        <div className="p-6 space-y-6 overflow-y-auto max-h-[70vh]">
          {/* Top 3 High-Impact Metrics */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            {/* Metric 1: Files Deleted */}
            <div className="bg-[#161B2A] border border-[#1F293D] rounded-xl p-4 flex flex-col items-center justify-center text-center shadow-sm">
              <div className="w-8 h-8 rounded-full bg-rose-500/10 text-rose-400 flex items-center justify-center mb-2">
                <Trash2 className="w-4 h-4" />
              </div>
              <div className="text-2xl font-extrabold text-slate-100 font-mono tracking-tight">
                {report.filesDeleted.toLocaleString()}
              </div>
              <div className="text-xs text-slate-400 font-semibold mt-0.5">
                Files Cleaned & Deleted
              </div>
            </div>

            {/* Metric 2: Space Freed */}
            <div className="bg-[#161B2A] border border-[#1F293D] rounded-xl p-4 flex flex-col items-center justify-center text-center shadow-sm">
              <div className="w-8 h-8 rounded-full bg-emerald-500/10 text-emerald-400 flex items-center justify-center mb-2">
                <HardDrive className="w-4 h-4" />
              </div>
              <div className="text-2xl font-extrabold text-emerald-400 font-mono tracking-tight">
                {report.spaceFreedMB > 1024
                  ? `${(report.spaceFreedMB / 1024).toFixed(2)} GB`
                  : `${report.spaceFreedMB} MB`}
              </div>
              <div className="text-xs text-slate-400 font-semibold mt-0.5">
                Storage Space Reclaimed
              </div>
            </div>

            {/* Metric 3: Memory / Standby RAM Freed */}
            <div className="bg-[#161B2A] border border-[#1F293D] rounded-xl p-4 flex flex-col items-center justify-center text-center shadow-sm">
              <div className="w-8 h-8 rounded-full bg-cyan-500/10 text-cyan-400 flex items-center justify-center mb-2">
                <Cpu className="w-4 h-4" />
              </div>
              <div className="text-2xl font-extrabold text-cyan-400 font-mono tracking-tight">
                {report.memoryFreedMB > 0 ? `${report.memoryFreedMB} MB` : 'Optimized'}
              </div>
              <div className="text-xs text-slate-400 font-semibold mt-0.5">
                Standby RAM Released
              </div>
            </div>
          </div>

          {/* Secondary Stats Strip */}
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-2.5 text-xs">
            <div className="p-3 bg-[#0B0F1A] border border-[#1F293D] rounded-lg">
              <div className="text-slate-400 font-medium">Safe In-Use Locks:</div>
              <div className="font-semibold text-amber-300 mt-0.5 flex items-center space-x-1">
                <ShieldCheck className="w-3.5 h-3.5" />
                <span>{report.lockedFilesSkipped} files bypassed safely</span>
              </div>
            </div>

            <div className="p-3 bg-[#0B0F1A] border border-[#1F293D] rounded-lg">
              <div className="text-slate-400 font-medium">Services Recycled:</div>
              <div className="font-semibold text-slate-200 mt-0.5">
                {report.servicesRecycled.length > 0
                  ? report.servicesRecycled.join(', ')
                  : 'No service restarts required'}
              </div>
            </div>

            <div className="p-3 bg-[#0B0F1A] border border-[#1F293D] rounded-lg col-span-2 sm:col-span-1">
              <div className="text-slate-400 font-medium">Network Stack:</div>
              <div className="font-semibold text-cyan-300 mt-0.5">
                {report.networkActions.length > 0 ? report.networkActions[0] : 'Preserved'}
              </div>
            </div>
          </div>

          {/* Itemized Executed Operations */}
          <div className="space-y-2">
            <div className="flex items-center justify-between text-xs">
              <span className="font-bold uppercase tracking-wider text-slate-300">
                Executed PowerShell Operations ({report.detailedLogSummary.length})
              </span>
              <span className="text-emerald-400 font-medium text-[11px]">All Passed</span>
            </div>

            <div className="bg-[#080B12] border border-[#1F293D] rounded-lg p-3 space-y-2 font-mono text-xs max-h-48 overflow-y-auto">
              {report.detailedLogSummary.map((item, idx) => (
                <div key={idx} className="flex items-start space-x-2 text-slate-300">
                  <span className="text-emerald-400 font-bold">✓</span>
                  <span className="leading-relaxed">{item}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="bg-[#0A0D17] px-6 py-4 border-t border-[#1F293D] flex flex-wrap items-center justify-between gap-3">
          <button
            onClick={onViewTerminal}
            className="px-4 py-2 bg-[#161B2A] hover:bg-[#1E293B] text-cyan-400 hover:text-cyan-300 rounded-lg text-xs font-semibold border border-[#1F293D] hover:border-cyan-500/40 flex items-center space-x-2 transition-all cursor-pointer"
          >
            <Terminal className="w-3.5 h-3.5" />
            <span>View Full PowerShell Terminal Stream</span>
          </button>

          <button
            onClick={onClose}
            className="px-5 py-2 bg-gradient-to-r from-[#0284C7] to-[#2563EB] hover:from-[#0369A1] hover:to-[#1D4ED8] text-white rounded-lg text-xs font-bold shadow-md shadow-sky-950/40 border border-sky-400/30 transition-all cursor-pointer active:scale-95 flex items-center space-x-1.5"
          >
            <ArrowLeft className="w-3.5 h-3.5" />
            <span>Return to Live Admin Monitor</span>
          </button>
        </div>
      </div>
    </div>
  );
};
